### ISSUE TITLE
Service ticker

### ISSUE THREAD

**Issue by waltergrimmvie** [winstongubantes/MatchaBackgroundService#7]
Hi, thanks for the really great tool,

The sample shows you can set a tick to do something, I would require the class to be constantly running in background as service like in windows, since I have some signalr hubs in threads in the service, that will write to sqlite,

Any suggestions for on how to have this constantly running, of will the signal listener stay active after first call?

Thanks

Walter

**Comment by winstongubantes** [comment]
Hi @waltergrimmvie 

Thanks i appreciate it, btw regarding with your question about running the background services constantly on the background just like windows (the answer is both yes and no), YES when you are using Android devices which have less than the Oreo OS version, NO when you are using Android Devices which have an Oreo OS and for all iOS versions. The execution time limit is handled by Operating System.

For more info about Backgrounding in Android please check the link [HERE](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/services/). 

For more info about Backgrounding in iOS please check the link [HERE](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/backgrounding/ios-backgrounding-techniques/).

**Comment by waltergrimmvie** [comment]
Hi Winston,

I really dont wont to bother you, but can I please have one more question bevore I start with your tool, which seems to be the only way for newbee on Xamarin walking this path somehow.

I another post you reply:

Hi @RomaRudyak , we have a new update which supports Non-repeatable execution of your IPeriodicTask in version 1.0.5461. We have also updated the documentation. Hope it helps

SO i need to run something like the SW have now (linkedin FB etc) , where the notifications pop up all night, screen dark, app not in forground but running.

I foudn these infos:
1. There are foreground services, which can call background services
2. There are long runnign services, which i could call repeatadly (see message to Rudyak)
3. There are the short 3 min alowed tasks for android and IOS 

I need to have open several signalr hubs to multiple servers to recieve push messages. What would you suggest would be the best solution for this. MY SW must be running in the startup of Android at most basic.
(my connection ID etc are all in a RAMDISK, so server usage for updating the connid is not very significan

**Comment by winstongubantes** [comment]
Hi @waltergrimmvie 

Here is the  answer to your question, i enumerated it below, i will also add a side note.

1.  There are foreground services, which can call background services
-ANS: yes foreground may run a background services, personally haven't tried it. But in our plugin we are only running backgroundservices. PS: i think we have used foreground for UWP only because we have issue with the UWP native background service.

2.  There are long running services, which i could call repeatadly (see message to Rudyak)
-ANS: yes we are running long running services, and there is a method called StartJob which is called repeteadly at a specified interval(Set as property). Make no mistake about long running services it can be terminated by the OS (Android Oreo or later and iOS) specifically when the app is not in foreground(which mean closed)

3.  There are the short 3 min alowed tasks for android and IOS
-ANS: for iOS yes its 3 minutes before it is terminated given the app is not in foreground(which mean closed) and for Android Oreo i think its beyond 3 minutes (this is managed by OS).

Note: linkedin and facebook uses firebase for notification and this cannot be achieved using Background service alone. I think they have some sort of Service Job running on their server to invoke firebase notification at an interval.

**Comment by waltergrimmvie** [comment]
HI thnxs,

ok, seen these things, but just starting to understand. So there is no reliable way to ensure a push system for notifications to your app. All articles tell you basic stuff, but in the end, if your app is runnign signalr, it might be the case that you will not recieve any info for a while if your backgroud service gets killed.

So best way is to each call server if there is something to pick up, like i have been doing for years (just set bit in Ramdisk, and which api), or call the 3 min task every 2 and update the signalR connID
